### ISSUE TITLE
Window Transparency Setting Messes with Window Size, Style, and Randomly Remains Opaque

### ISSUE THREAD

**Issue by D-Maxwell** [pulsar-edit/pulsar#1046]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

After noticing that #948 had been considered for implementation, I couldn't help but upgrade to the latest release and enjoy an acrylic or even a plain blurred background for this great IDE ; to my surprise, I was met with quite a few annoyances, some of which looked terrible, and others outright preventing any use of the IDE as it remained in a collapsed state, unable to be focused, along an empty and tiny preview window from the taskbar entry. (this may or may not happen after disabling Window Transparency, postponing the restart, and enabling it once more, before then restarting, although I am now unable to reproduce this last issue)

### Pulsar version

1.118.0

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10 Pro 22H2 19045.2788

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

As seen in this first picture, the document's size does not match that of the window. I have also found it impossible to resize the window by its edges, although it does work through AltSnap (a Window Management Script). In such a scenario, the maximise button has no effect either.
![image](https://github.com/pulsar-edit/pulsar/assets/98100481/3f8c9bf5-b3ab-40e5-ae90-29b82eb2a248)

Maximising the window through AltSnap --given the inefficiency of the intended button-- will either yield a black background in place of a transparent view --a screenshot for which I lack--, or will result in the title bar reverting to some XP-esque aesthetic.
![image](https://github.com/pulsar-edit/pulsar/assets/98100481/bf873d16-c760-476b-8e3f-3b6927350d0a)

As previously mentioned, at times, the window will spawn without respect to its last set size, and will default to the minimum window size ; which, in conjunction to the document not filling the whole window for some reason, leads to a purely empty window, unless manually expanded ; once again, through the use of a script, as the edges refuse to be considered as such upon hovering.
![image](https://github.com/pulsar-edit/pulsar/assets/98100481/928e9ce4-dac8-417c-a376-a37b0cb47d1d)

### Additional Information:

I am quite disappointed seeing this feature that I for one had greatly anticipated, and I would love for it to become usable.

**Comment by D-Maxwell** [comment]
![image](https://github.com/pulsar-edit/pulsar/assets/98100481/25bcb853-2298-455c-a80c-8b2c7d67ad9d)
After some amount of styling, I could get it to look somewhat good ; that being said, resizing the window and opening the editor remain quite painful.

**Comment by confused-Techie** [comment]
@D-Maxwell While I appreciate the issue, this is very much known.

We tried to get this across in the setting description of `Allows editor windows to be see-through. When this setting is enabled, UI themes and user stylesheets can use background colors with an alpha channel to make editor windows translucent. Takes effect after a restart of Pulsar.`. Which the important part to note is "UI themes and user stylesheets can use...".

We are aware that just enabling this doesn't really look that great. There were attempts to make this feature usable on our default provided themes, but doing so was much much easier said than done. Leaving us to essentially offer the ability for "community UI themes and user stylesheets" to utilize this feature. 

We know you wanted this feature, so we wanted to make sure we could support you and the rest of the community in having it, even if we don't have the time ourselves to make a stylesheet that makes it perfect. 

Considering the time you spent working on your user stylesheet to make this work, I'd highly recommend that you could publish those changes as a community UI theme for everyone else, or even if you don't want to, we could look at using `pulsar-cooperative` to manage the package while getting the changes you've made to make this available to everyone.

But otherwise I apologize if this was an underwhelming change, but our goal in the PR that was merged was to make this behavior possible rather than take advantage of it completely. While that may or may not change in the future, I'd love to see someone from the community be able to turn it into something truly great, now that it is possible at all.

(I'd like to note I don't speak for DeeDeeG who authored the changes themselves, but was communicating with them through the difficulties in attempting to utilize these features in built in themes, and may have supported the current course of action in simply making the feature possible.)

**Comment by savetheclocktower** [comment]
I'll admit I was surprised to see the difference between the implied dimensions of the window (as indicated by the title bar and placement of the close/minimize/maximize buttons) and the dimensions that we actually occupy. Was that a known issue?

**Comment by D-Maxwell** [comment]
> I'll admit I was surprised to see the difference between the implied dimensions of the window (as indicated by the title bar and placement of the close/minimize/maximize buttons) and the dimensions that we actually occupy. Was that a known issue?

@confused-Techie seems to have focused on exactly the one thing... that I had been expecting.
At no point had I expected Pulsar to incorporate stylings that made use of the window's ability to render transparently. The initial reason I reported this issue --the same as for why i believe its existence was required-- had all to do with every other issue I've (actually) mentioned. Again, at no point was I expecting a ready made them to be bundled and enabled upon toggling on the setting.
I knew I would have to be spending an hour or two getting familiar and experimenting with Atom's inner HTML layout, in order to create my own theme taking advantage of this newly merged feature.

I would certainly prefer for you to focus on the other issues this seems to have brought --and that I have reported above--, as I reckon you must have misunderstood me by expecting my own expectations to be such that Pulsar would automatically "look good" with this option on.

**Comment by D-Maxwell** [comment]
> Considering the time you spent working on your user stylesheet to make this work, I'd highly recommend that you could publish those changes as a community UI theme for everyone else, or even if you don't want to, we could look at using `pulsar-cooperative` to manage the package while getting the changes you've made to make this available to everyone.
> 
> But otherwise I apologize if this was an underwhelming change, but our goal in the PR that was merged was to make this behavior possible rather than take advantage of it completely. While that may or may not change in the future, I'd love to see someone from the community be able to turn it into something truly great, now that it is possible at all.

I had indeed thought of releasing my humble --somewhat messy and hastily put together-- stylesheet, although I had never done that in the past. I may consider getting to it once I am done covering all use cases (as for some reason some panels are unaffected by the global rules I have defined, such as the Settings pane), and once I finish tidying it up.

**Comment by D-Maxwell** [comment]
> I'll admit I was surprised to see the difference between the implied dimensions of the window (as indicated by the title bar and placement of the close/minimize/maximize buttons) and the dimensions that we actually occupy. Was that a known issue?

I haven't found any related ones prior to opening this issue.
As the entirety of the DOM is restrained by foreign constraints unaccessible to me, I stand unable to fix the improper dimensions of the page within its window, even as a bodge.

Would you be aware of any clues as to where exactly the root cause may lie ?

**Comment by savetheclocktower** [comment]
> Would you be aware of any clues as to where exactly the root cause may lie ?

No; I have no experience with this area of Electron.

This is not very high on my list of concerns right now, but that's just because I've got six other Pulsar-related tasks going at any one time. Another team member may be able to run some quick experiments to figure out what's going on, but if not, this might just be a symptom of the fact that we're on an old version of Electron. @mauricioszabo runs a version of Pulsar updated to the latest Electron; he might be able to check this for you if he's in a good mood.

@D-Maxwell, would it be possible for you to isolate some small amount of CSS that would set a transparent background on most themes? If not, it's OK; it'd just be nice to have something that a user could paste into their stylesheet to test transparency instead of having to create a whole theme.

**Comment by D-Maxwell** [comment]
> @D-Maxwell, would it be possible for you to isolate some small amount of CSS that would set a transparent background on most themes? If not, it's OK; it'd just be nice to have something that a user could paste into their stylesheet to test transparency instead of having to create a whole theme.

Sure, I was already planning on doing something akin to this.
That being said, where should I publish this ? I have no prior experience packaging add-ons for Atom.

Looking forward to those issues being fixed, but take your time, this is no matter rendering the program unusable.

**Comment by savetheclocktower** [comment]
> Sure, I was already planning on doing something akin to this. That being said, where should I publish this ? I have no prior experience packaging add-ons for Atom.

I mean something more like _the least amount of CSS/Less that a user can apply to turn their current theme transparent_. Ideally this would be something small enough to paste into this issue or into a Gist.

If it helps, try the following more specific exercise:

* Set your UI theme to One Dark.
* Open your user stylesheet.
* See how much CSS you'd need to add to your user stylesheet to override One Dark and make the theme exhibit transparency.
* Take that CSS and paste it into a code block in this issue.

**Comment by D-Maxwell** [comment]
Literal values were decided arbitrarily, but not including them would yield an absolutely illegible workspace.
I reckon you would be interested in the "Absolutely Necessary" section.

```css
// Translucence //

/// Absolutely Necessary ///

atom-text-editor {
	background-color: rgba(0,0,0, calc(2/3));

	// bodge, bad dobby bad
	& *:not(:is(atom-overlay, .selection.region)) {
		// why should every sub-component have its own background declared independently...
		background: none !important;
	}
}


atom-panel-container.footer > atom-panel.panel-footer {
	background-color: rgba(0,0,0, calc(1/2));

	& > * { background: none; }
}


html, atom-workspace {
	background: transparent;
}

.atom-dock-mask {
	background-color: transparent;

	& * {
		background: none;
	}
}


/// Recommended ///

.atom-dock-mask .item-views {
	background: rgba(0,0,0, calc(3/5)); // 2/3 as well ?
}

.atom-dock-mask * {
	color: white;
}


.pane > ul[is="atom-tabs"] {
	background: none;

	& > li[is="tabs-tab"] {
		--_opacity: calc(1/2);
		background-color: rgba(0,0,0, var(--_opacity)) !important;

		&.active {
			--_opacity: calc(2/3);
		}

	}

}



/// Eye Candy ///

// text selection highlight
atom-text-editor .selection.region {
	// not sure what the default opacity should be, this may turn out overly soft for most, despite being subtile enough to my eyes
	background-color: rgba(0,0,0,0.25);
}

// entry selection highlight
.tool-panel.tree-view ol.list-tree > li::before {
	opacity: 0.5; // quick fix, to reconsider
}

.pane > ul[is="atom-tabs"] {
	// for some reason box-shadow is used as a border ???
	box-shadow: none;

	& > li[is="tabs-tab"] {
		// this could mayhaps be turned into a slight gap
		border: none; // border is overdrawn by accent, only visible past three open tabs
	}

}

.atom-dock-inner, atom-pane.pane {
	border: none !important;
}

.tab-bar .tab:last-of-type {
	// return of the box shadow border
	box-shadow: none;
}



// AutoComplete Modal [WIP] //

atom-overlay[class*="autocomplete"] {
	position: absolute !important;
}

atom-overlay[class*="autocomplete"] > autocomplete-suggestion-list {
	backdrop-filter: blur(40px);
	background-color: rgba(0,0,0,0.25) !important;
}
```
