### ISSUE TITLE
Less should be able to communicate with our config syste,

### ISSUE THREAD

**Issue by savetheclocktower** [pulsar-edit/pulsar#1093]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Let me try to both expand and summarize [what I said here](https://github.com/pulsar-edit/pulsar/issues/1087#issuecomment-2332960084).

When Pulsar upgraded to a recent version of [Less](https://lesscss.org/) last year, it enabled a new style of plugin. Less plugins can be declared within a given scope, then used in that scope:

```js
// utilities.js
function simpconfigeConfig (keyPath) {
  return atom.config.get(keyPath.value);
}

module.exports = {
  install: function(_less, _pluginManager, functions) {
    functions.add('config', config);
  }
};
```

```less
@plugin "utilities.js";

body {
  font-size: config('some-theme.fontSize');
}
```

This is the simplest possible version of this idea. I find it very compelling, especially compared to the hacky things that I've seen themes do (and done myself!) in order to make themes more configurable. (When a setting changes, regenerate a file on the fly that defines some variables, then disable and re-enable the package!)

This approach can even be extended to allow the user to define fallback values or to combine bare numeric values with units:

```less
@plugin "utilities.js";

body {
  font-size: config('some-package.fontSize', 13px);
  line-height: config('some-package.lineHeight', 1, 'rem');
}
```

This is the easy part.

The hard part is how frequently that function would get called in the course of stylesheet generation.

---

Suppose we wanted to make `@font-size` configurable in a UI theme. That's a great idea, since practically all UI text uses (or defines itself relative to) the value of `@font-size` — and it can't easily be changed from a user stylesheet.

If a theme defined a line like this in its `ui-variables.scss`…

```less
body {
  @font-size: config('some-package.fontSize', 13px);
}
```

…it'd be defining it in a file that is requested by practically every non-editor stylesheet in the app. There's a strong expectation that importing `ui-variables.less` is like importing a flat file of dumb exports.

That's because the style sheets are evaluated in a Pulsar context, but each compiled stylesheet encounters its own reference to `utilities.js`, and loads that file fresh each time. This makes it currently impossible to (e.g.) cache config lookups on the theory that they won't change during a stylesheet regeneration — you can try, but the cache will get wiped away when Less is done building that file.

### What benefits does this feature provide?

Elegance! No longer having to use style hacks! Perhaps even an emerging convention about what should be configurable in a UI theme. #1087 was useful for illustrating how weird it is that we have a setting for editor font size, but not for the chrome around the editor.

### Any alternatives?

Suppose I change a package's font size via a setting. That package has to regenerate all its stylesheets to reflect the new `@font-size` variable. Then all the people that depend on _those_ stylesheets have to adjust _their_ stylesheets. Over the course of this process, `ui-variables.less` is included dozens of times, and those calls can't practically share state with one another. (Unless I've overlooked something; it happens pretty regularly!)

I don't know how to pull that off, but it'd be nice.

**Comment by savetheclocktower** [comment]
There are related issues here and I've mentioned some of them in Discord:

1. Our Less compilation strategy assumes that it doesn't have to recompile a file if its contents haven't changed. But a `config` function throws a wrench in that assumption! And it’s not easy to get Pulsar to recompile a stylesheet that it thinks hasn't changed.
2. Less is designed to be late binding, and brags about it:

    ```less
    @font-size: 12px;
    p { font-size: @font-size; }
    @font-size: 14px;

    // Results in CSS:
    p { font-size: 14px; }
    ```

    This works because Less does two passes; it resolves all variable references before it produces any output. So you'd think that you could just redefine `@font-size` in the user stylesheet and have it reflected in _all_ stylesheets, right? Presumably that would work _if_ we assembled all stylesheets and processed them in a batch somehow — but we don't. Each separate package has its styles processed in isolation from others.

    If we could somehow change this, it would solve many of the problems listed above, but also create some new problems. We'd have to make sure that one badly-written stylesheet wouldn't wreck the styles for the entire editor, and we'd also have to make sure that a variable defined in one stylesheet doesn't leak into a different stylesheet from a different package. (I'm sure that lots of stylesheets incidentally use the same local variable names and don't expect them to clash with one another.) I haven't looked into it yet, but I'm skeptical that we could thread that needle.

**Comment by savetheclocktower** [comment]
The good news: I managed to write a Less plugin that _largely_ allows someone to perform math on `@foo` when `@foo` is itself assigned to a CSS variable (like `var(--foo)`).

```less

@font-size: 13px;
h1 { font-size: (@font-size * 2); }

// Produces:
h1 { font-size: 26px; }

// ---

@font-size-var: var(--font-size);
h1 { font-size: (@font-size-var * 2); }

// Produces:
h1 { font-size: calc(var(--font-size) * 2); }
```

In other words, it turns compile-time evaluations into runtime evaluations.

The bad news is that there are a number of math functions — `round`, `floor`, `ceil`, `mod`, and some trigonometric functions — that also operate on numbers, and they're used in several places in various `.less` files. To translate these to runtime evaluations would require that equivalent functions exist _in CSS_, and they don't in Pulsar.

But they will eventually! These functions were added to the CSS spec and are present in Chrome 125, which means they'll be available to us when we're able to upgrade to the latest Electron.

This may still be a very silly thing to do, but we could at least play around with it and see if it works. One day we won't need Less variables anymore, and this may be one way we can gently migrate old stylesheets.
