### ISSUE TITLE
markdown-preview cannot render nested YAML objects

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/pulsar#628]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Nested objects in the YAML frontmatter don't render correctly.

Take this frontmatter used on our website:

```yml
---
title: Community areas
path: /community/
sitemap:
  priority: 0.9
  changefreq: "weekly"
---
```
This is how `markdown-preview` renders it:
![image](https://github.com/pulsar-edit/pulsar/assets/58074586/2ebe480f-da29-4df9-a2ab-639dc25ae045)

vs how GitHub renders it:
![image](https://github.com/pulsar-edit/pulsar/assets/58074586/b0bc5e7d-407e-4d85-95bc-49864a5f6ec5)

### Pulsar version

1.106.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

LM 21.1

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

- Open a .md document or set grammar to markdown
- Add the following to the top of your document:

```yml
---
title: Community areas
path: /community/
sitemap:
  priority: 0.9
  changefreq: "weekly"
---
```
  
- Select `Markdown Preview: Toggle` from command palette
- Note that the `sitemap` renders as `[object Object]`
