### ISSUE TITLE
[core]: Style Manager Transforming Deprecated Math Usage Fails on Variables

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#650]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

As originally reported over on our [discussions](https://github.com/orgs/pulsar-edit/discussions/201), lead me to discover that the automatic [transforming of deprecated math usage in less style sheets](https://github.com/pulsar-edit/pulsar/pull/611) will fail to apply to variables in Less.

That's because the [regex](https://github.com/pulsar-edit/pulsar/blob/master/src/style-manager.js#L439) used in Style Manager to match mathematical expressions, was never built with any consideration for variables. So that may mean we need to rework that expression to support variables as well, while ensuring to not start capturing any false positives. Since really I'd much rather the automatic upgrade behavior have more false negatives than false positives. Since imo it's better to leave something broken as broken, than break something that's correct.

Thinking of solutions, while we could expand the regex to support looking for any text of valid variables prefixed by `@`, but I do worry about an increase in false positives. So it may be beneficial to in addition add a maximum length of any matched string. To avoid a situation where the match goes into any kind of selectors, and cap it at say 10 characters?

### Pulsar version

1.107.1

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Install [`tool-bar`](https://web.pulsar-edit.dev/packages/tool-bar)
2. Add some mystery package to use it
3. Find visual errors as described on the discussion 

OR

1. Copy the regex linked above from Style Manager into something like Regex101
2. Copy the mathematical expression that needs to be translated into Regex101
3. View the lack of matches

### Additional Information:

* The effected Less Style Sheet in [`tool-bar`](https://github.com/atom-community/tool-bar/blob/master/styles/tool-bar.less#L145C9-L145C29)
* Example of the regex failing to catch variables: [here](https://regex101.com/r/qIi6IN/1)

Example snippet:

```less
.tool-bar-btn {
      height: @size + (@button-border-size * 2);
      min-width: @size + (@button-border-size * 2);
      &:before {
        font-size: @size / 2;
        line-height: @size;
      }

      &:not(:empty) {
        font-size: @size / 2;
        line-height: @size;
        padding: 0 @size / 4;
        &:before {
          padding-right: @size / 4;
        }
      }
    }
```
