### ISSUE TITLE
Pulsar `tab` key failing

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#692]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

While writing in the new YAML Tree-Sitter Grammar, I encountered an issue where intermittently my tab would fail.

I haven't yet been able to determine exactly what causes it, but switching to the TextMate grammar does seem to resolve the issue for me, although that seems very strange. If I'm able to find replication steps, I'll provide them, otherwise I've provided the file I was working on below.

Attempting to run tab in a window with that following content and hitting the `tab` key results in the following:

```
At C:\Users\USER\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1323

TypeError: Cannot destructure property 'buffer' of 'instance' as it is undefined.
    at Object.lastTextOnRow (/app.asar/src/scope-resolver.js:622:11)
    at ScopeResolver.applyTest (/app.asar/src/scope-resolver.js:260:43)
    at ScopeResolver.test (/app.asar/src/scope-resolver.js:343:19)
    at ScopeResolver.store (/app.asar/src/scope-resolver.js:396:15)
    at WASMTreeSitterLanguageMode.suggestedIndentForBufferRow (/app.asar/src/wasm-tree-sitter-language-mode.js:1289:26)
    at TextEditor.suggestedIndentForBufferRow (/app.asar/src/text-editor.js:5641:20)
    at Selection.indent (/app.asar/src/selection.js:988:41)
    at /app.asar/src/text-editor.js:4476:52
    at /app.asar/src/text-editor.js:1801:33
    at Array.map (<anonymous>)
    at /app.asar/src/text-editor.js:1800:60
    at TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1320:16)
    at TextEditor.transact (/app.asar/src/text-editor.js:2467:24)
    at /app.asar/src/text-editor.js:1799:19
    at TextEditor.mergeSelections (/app.asar/src/text-editor.js:4053:20)
    at TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:4015:10)
    at TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1798:17)
    at TextEditor.indent (/app.asar/src/text-editor.js:4476:10)
    at /app.asar/src/register-default-commands.js:625:19)
    at /app.asar/src/register-default-commands.js:691:76
    at TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1320:16)
    at TextEditor.transact (/app.asar/src/text-editor.js:2467:24)
    at /app.asar/src/register-default-commands.js:691:13)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:405:43)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:153:34)
```

### Pulsar version

1.107.2023081804

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

1. Create a file YAML file with the following content:

<details>
<summary>YAML File</summary>

```yaml
name: Build Pulsar Binaries

on:
  pull_request:
  push:
    branches: [ 'master' ]

env:
  # Variables needed for build information
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYTHON_VERSION: '3.10'
  NODE_VERSION: 16
  # Below variables allow us to quickly control visual tests for each platform
  RUN_WINDOWS_VT: false
  RUN_LINUX_VT: true
  RUN_MACOS_VT: false

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Git Submodule
      run: |
        git submodule init
        git submodule update

    - name: Check Pulsar Version
      if: ${{ matrix.os != 'windows-latest' }}
      run: sed -i -e "s/[0-9]*-dev/`date -u +%Y%m%d%H`/g" package.json

    - name: Check Pulsar Version - Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: (Get-Content package.json) -replace '[0-9]*-dev', (date -u +%Y%m%d%H) | Set-Content -Path package.json

    - name: Install Pulsar Dependencies
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: yarn install --ignore-engines
        on_retry_command: rm -R node_modules

    - name: Build Pulsar
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: |
          yarn build
          yarn run build:apm

    # macOS Signing Stuff
    - name: Build Pulsar Binaries (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      # env:
      #   CSC_LINK: ${{ secrets.CSC_LINK }}
      #   CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      #   APPLEID: ${{ secrets.APPLEID }}
      #   APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
      #   TEAM_ID: ${{ secrets.TEAM_ID }}
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: yarn dist

    - name: Build Pulsar Binaries
      if: ${{ matrix.os != 'macos-latest' }}
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: yarn dist

    - name: Upload Binary Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }} Binaries
        path: ./binaries/*

    - name: Test Binary - Linux
      if: ${{ (matrix.os == 'ubuntu-latest') && env.RUN_LINUX_VT }}
      run: |
        rm -R node_modules/electron; yarn install --check-files
        ./binaries/*AppImage --appimage-extract
        export BINARY_NAME='squashfs-root/pulsar'
        mkdir -p ./tests/videos
        Xvfb -screen 0 1024x768x24+32 :99 & nohup ffmpeg -video_size 1024x768 -f x11grab -i :99.0 ./tests/videos/out.mpg & DISPLAY=:99 PLAYWRIGHT_JUNIT_OUTPUT_NAME=report.xml npx playwright test --reporter=junit,list

    - name: Test Binary - Windows
      if: matrix.os == 'windows-latest' && env.RUN_WINDOWS_VT == true
      # TODO: Convert script to PowerShell
      run: |
        mkdir extracted; tar -xf binaries/*zip -C ./extracted/
        export BINARY_NAME=./extracted/Pulsar.exe
        PLAYWRIGHT_JUNIT_OUTPUT_NAME=report.xml npx playwright test --reporter=junit,list || echo "Yeah, tests failed, Windows is like this"

    - name: Test Binary - macOS
      if: matrix.os == 'macos-latest' && env.RUN_MACOS_VT == true
      run: |
        export PATH="/usr/local/opt/node@16/bin:/usr/local/bin:$PATH"
        rm -R node_modules/electron; yarn install --check-files
        hdiutil mount binaries/Pulsar*dmg
        export BINARY_NAME=`ls /Volumes/Pulsar*/Pulsar.app/Contents/MacOS/Pulsar`
        PLAYWRIGHT_JUNIT_OUTPUT_NAME=report.xml arch -x86_64 npx playwright test --reporter=junit,list

    - name: Add binaries to Rolling Release Repo

    - name: Upload Video Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }} Videos
        path: ./tests/videos/**

```

</details>

2. Hit tab (Maybe, I haven't exactly worked out what causes it)
