### ISSUE TITLE
Publish GitHub Repository Dropdown Showing Overflowing Profile Icon

### ISSUE THREAD

**Issue by D-Maxwell** [pulsar-edit/pulsar#952]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

![image](https://github.com/pulsar-edit/pulsar/assets/98100481/f56a9c27-afe4-43cb-96d0-7b1ec214df81)

I think the above speaks for itself.

### Pulsar version

1.114.0

### Which OS does this happen on?

🪟 Windows

### OS details

10 Pro 22H2

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

In GitHub panel, click Publish & Initialise Repository.
Be greeted with a blinding, white filled dropdown, due to your user's profile icon spanning its whole width.

### Additional Information:

This seems like an easy issue to fix, as all it took to get it back to a seemingly normal state --non-jarring, at the very least-- was to explicitly tell two elements to size themselves according to the dimensions of their direct parent, as shown here :
![image](https://github.com/pulsar-edit/pulsar/assets/98100481/526cff2b-0f68-471d-b5f6-f6543777719f)
![image](https://github.com/pulsar-edit/pulsar/assets/98100481/fde394d4-878d-4417-b0d5-7400ab609cf9)

The following rules were used to quickly "fix" this :
```css
.Select-placeholder, .Select--single > .Select-control .Select-value {
	padding: unset;
}
.github-RepositoryHome-ownerOption {
	height: 100%;
}
.github-RepositoryHome-ownerAvatar {
	height: 100%;
	/*padding: 0.2em;*/
}
```
